<a href="https://colab.research.google.com/github/AustinKarki/75-Days-of-Coding-Challenge/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numeric python numpy
# pip install numpy
# list single direction  while array multidirection
# numpy works at multidirection array and also matrix
# store at multidirection array and also matrix

# 1. performance numpy array is faster(generally faster not super fast) than list in numeric computation power as internal representation is properly optimized
# 2.numpy has more functionality than list
# 3.array operation easy to use in proper way as library is more inhance and readable
import numpy as np

## Time comparision between numpy array and python lists

In [ ]:
import time
# ilteration vitra rakhda code la kati choti te step lai generate garxa
ilteration=100000000 #steps
# measure python list generation time
before = time.time()
list(range(ilteration))
after=time.time()
python_time=after-before
print("python time",python_time)

# measure numpy array generation time
import numpy as np
before = time.time()
np.arange(ilteration) # range in list while arange in numpy
after=time.time()
numpy_time=after-before
print("numpy time",numpy_time)

python time 11.61210298538208
numpy time 0.21920228004455566


In [ ]:
print(f"Numpy is {python_time/numpy_time} faster than regular Python.")
# single target and in numbers

Numpy is 52.97437135700309 faster than regular Python.


In [ ]:
from sklearn.datasets import load_breast_cancer
cancer_data=load_breast_cancer()
cancer_data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [ ]:
cancer_data["data"]

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
cancer_data["target_names"]

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
cancer_data["feature_names"]

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
cancer_data["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
cancer_data["data"].shape

(569, 30)

In [ ]:
cancer_data["data"][0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [ ]:
# cancer_data["data"].info() # no info in numpy

In [ ]:
a=np.array([1,2,3,4,5])
type(a) # n dimention array

numpy.ndarray

In [ ]:
a.ndim #dimention

1

In [ ]:
b = np.array(
    [[[[[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]],
    [[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]]],
    [[[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]],
    [[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9999], [9, 10, 11, 12]]]]],
    [[[[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]],
    [[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]]],
    [[[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]],
    [[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]]]]]
)

In [ ]:
b[0][1][1][1][1][3]

9999

In [ ]:
b.ndim

6

In [ ]:
b.shape

(2, 2, 2, 2, 3, 4)

In [ ]:
b[0][1][1][1][1][3]

9999


Squid Game Challenge - Game

In a hidden room, contestants discover an array shaped like a multi-dimensional puzzle. They must determine the dimensions of this array: how many layers exist and what is the total shape of this complex structure?

As they search for clues, one contestant must find the exact position of the hidden number five within a larger, grid-like array. Where will this elusive number be located among the surrounding values?

During a tense face-off, competitors learn they can modify a given array by adding ten to any value greater than fifty. They must quickly compute the new values, revealing the transformed array that holds the key to their survival.

The next challenge involves counting. Contestants face an array filled with numbers and must determine just how many times the mysterious number twelve appears among them. Will they find the key to victory hidden in plain sight?

In the final task, contestants must carefully slice through a given array to extract the first two rows from the last embedded section. By navigating the layers, they aim to reveal essential information that could alter the fate of their game.

In [ ]:
# e=np.array[]

In [ ]:
b = np.array([[[[0, 1], [2, 3]], [[4, 5], [6, 7]]], [[[8, 9], [10, 11]], [[12, 13], [14, 15]]]])
b.shape

(2, 2, 2, 2)

In [ ]:
b.ndim

4

In [ ]:
b[0][1][0][1]

5

In [ ]:

b[0][1][0][1]

5

In [ ]:
b[1][1][1][1] = (b[1][1][1][1]+10)

In [ ]:
b.size

16

In [ ]:
np.where(b==5)


(array([0]), array([1]), array([0]), array([1]))

In [ ]:
a=np.where(b>=15,b+10,b)
a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 35]]]])

In [ ]:
b[b==12].size

1

In [ ]:
b

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 25]]]])

In [ ]:
print(b[0][1])

[[4 5]
 [6 7]]


In [ ]:
print(b[-1][0])

[[ 8  9]
 [10 11]]


In [ ]:
print(b[0:1,0:1])

[[[[0 1]
   [2 3]]]]


In [ ]:
b

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 25]]]])

In [ ]:
print(b[0:2,0:1,0:1,1:2])

[[[[1]]]


 [[[9]]]]


In [ ]:
 a=[10,12,14,16]
 b=[]
 for i in a:
  b.append(i*2)
b


[20, 24, 28, 32]

In [ ]:
import numpy as np
aa=[10,12,14,16]
bb=np.array(a)
c=bb*2
c

array([20, 24, 28, 32])

In [ ]:
a=np.random.rand(2,3)
a

array([[0.39361518, 0.66662016, 0.55961039],
       [0.68328902, 0.08633024, 0.25838447]])

In [ ]:
b=np.random.rand(3,2)
b

array([[0.71082335, 0.2841029 ],
       [0.9180952 , 0.80091081],
       [0.84405042, 0.60378737]])

In [ ]:
np.matmul(a,b)

array([[1.36415101, 0.98361619],
       [0.78304669, 0.4192765 ]])

In [ ]:
b=np.random.randint(low=0, high=10, size=(2,3))
b


array([[7, 4, 5],
       [0, 6, 5]])

In [ ]:
w=np.random.randint(0,10,(1000,3))
e=np.random.randint(low=0,high=10,size=(3,1000))
q=np.matmul(w,e)
q.ndim
q.shape

(1000, 1000)

In [ ]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
np.matmul(array1,array2)

32

In [ ]:
array= np.array([3, 7, 10, 15, 19]).mean()
array

10.8

In [ ]:
array3=np.array([9, 2, 7, 5, 3]).max()
array3

9

In [ ]:
w=np.array([1, 2, 3, 4, 5, 6])
q=w.reshape(2,3)
q


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=np.random.randint(1,100,(5,5))
a

array([[16, 96, 54, 16, 24],
       [31, 73, 76, 21, 65],
       [31, 48, 25, 44, 57],
       [23, 59, 29, 39,  7],
       [55, 84, 56, 53, 52]])

In [ ]:
a.shape

(5, 5)

In [ ]:
a.ndim

2

In [ ]:
t=np.where(a>50,0,a)
print(t)

[[16  0  0 16 24]
 [31  0  0 21  0]
 [31 48 25 44  0]
 [23  0 29 39  7]
 [ 0  0  0  0  0]]


In [ ]:
y=np.random.randint(0,100,(20,))
y


array([83, 19, 17, 67, 22, 13, 52, 50, 81, 30, 22, 59, 98, 14, 34, 77, 12,
       48, 81, 36])

In [ ]:
y.ndim

1

In [ ]:
y.reshape(4,5)

array([[83, 19, 17, 67, 22],
       [13, 52, 50, 81, 30],
       [22, 59, 98, 14, 34],
       [77, 12, 48, 81, 36]])

In [ ]:
o=np.random.rand(3,3)
o

array([[0.08645732, 0.14622242, 0.35969505],
       [0.23251793, 0.309313  , 0.12815435],
       [0.55641947, 0.15528415, 0.93955536]])

In [ ]:
np.where(o<0.5,0,o)

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.55641947, 0.        , 0.93955536]])

In [ ]:
new=np.random.randint(1,100,(100,))
u=new.reshape(10,10)
new.reshape(10,10).sum(axis=1)

array([553, 620, 506, 456, 577, 386, 671, 403, 556, 463])

In [ ]:
l=[]
for i in u:
  l.append(i.sum())
l


[553, 620, 506, 456, 577, 386, 671, 403, 556, 463]

In [ ]:
t=np.random.randint(1,10,(4,4))
i=[]
for i in t:
  ma=i.max()
  y=np.where(t==ma)
  print(y)




(array([0, 3]), array([3, 1]))
(array([1, 2]), array([2, 0]))
(array([1, 2]), array([2, 0]))
(array([2, 3]), array([1, 2]))


In [ ]:
one=np.random.randint(1,10,(50,))
mean=one.mean()
std=one.std()
print(mean,std)


5.38 2.4074052421642684


In [ ]:
nn=np.random.randint(0,8,(3,3))
print(nn)
np.random.shuffle(nn)
print(nn)


[[0 5 6]
 [5 6 7]
 [1 2 5]]
[[1 2 5]
 [0 5 6]
 [5 6 7]]


In [ ]:
fg=np.random.randint(1,10,(5,6))
replace=np.where(fg%2!=0,-1,fg)
replace

array([[-1, -1,  2, -1,  2,  6],
       [-1, -1, -1, -1, -1, -1],
       [ 8,  2, -1, -1,  4, -1],
       [-1,  4, -1,  4, -1,  4],
       [ 2, -1,  2, -1,  6, -1]])

In [ ]:
import numpy as np
s=np.random.rand(5,6)
print(s)
print()
new=np.sort(s,axis=0)[::-1]
print(new)

[[0.74208304 0.44312483 0.90024919 0.2587031  0.02847711 0.70835499]
 [0.52089238 0.0712034  0.61964904 0.42714217 0.53100111 0.55783728]
 [0.85879925 0.00885202 0.54192721 0.67233394 0.13453557 0.04097048]
 [0.08548219 0.56863039 0.62286797 0.28160492 0.39918094 0.686942  ]
 [0.69164778 0.32303278 0.38331806 0.9230201  0.59979749 0.38211607]]

[[0.85879925 0.56863039 0.90024919 0.9230201  0.59979749 0.70835499]
 [0.74208304 0.44312483 0.62286797 0.67233394 0.53100111 0.686942  ]
 [0.69164778 0.32303278 0.61964904 0.42714217 0.39918094 0.55783728]
 [0.52089238 0.0712034  0.54192721 0.28160492 0.13453557 0.38211607]
 [0.08548219 0.00885202 0.38331806 0.2587031  0.02847711 0.04097048]]


In [ ]:
oo=np.random.rand(3,3)
su=np.sum(oo,axis=1)
su
di=np.divide(oo,su)
di


array([[0.36894788, 0.39641761, 0.23794896],
       [0.44985218, 0.26549279, 0.48186497],
       [0.39604175, 0.0590492 , 0.40688396]])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.linspace(0,3,4) # space should be 1 more than total

array([0., 1., 2., 3.])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6],[1,3,5]])
print(array.T)
print(np.transpose(array))


[[1 4 1]
 [2 5 3]
 [3 6 5]]
[[1 4 1]
 [2 5 3]
 [3 6 5]]
